### ISSUE TITLE
Suggestion: make porting work in progress more visible

### ISSUE THREAD

**Issue by vaskas** [BerryFarm/berrymuch#16]
## Problems

* There is a lot of interesting porting work cooking in a branch: https://github.com/berryamin/berrymuch/tree/develop/bootstrap
  * This work is not directly visible - a random web visitor won't jump into the develop branch straight off the bat
* We need to ensure the build scripts are consistent between master and develop
  * The only solution is rebasing develop against master constantly which takes time and effort and easy to forget about
* We want to ensure seamless transition between ports in progress and the stable ones

## Suggestion

Once / if https://github.com/berryamin/berrymuch/pull/13 gets merged:
1. Create a `ports-wip/` directory at the top level
2. Move all the `develop` ports in there
3. Delete the `develop` branch for good

**Comment by vaskas** [comment]
https://github.com/jasperla/openbsd-wip are running a somewhat similar model. WIP ports are visible and easy to collaborate on. Once the work is done the ports graduate into the official repository.

**Comment by matahariku** [comment]
Hmm good exercice to play with git namespaces .. I'll git them a try
