### ISSUE TITLE
cronie: segfault when using crontab -e

### ISSUE THREAD

**Issue by berryamin** [BerryFarm/berrymuch#19]
<pre>

bash-5.0$ ./sbin/crond
/var/tmp/spool/cron: No such file or directory
/var/tmp/spool/cron: mkdir: No such file or directory
bash-5.0$ mkdir /var/tmp/spool
bash-5.0$ mkdir /var/tmp/spool/cron
bash-5.0$ ./sbin/crond
bash-5.0$ crontab -e

Process 228794634 (crontab) terminated SIGSEGV code=1 fltno=11 ip=08049e50(/accounts/1000/appdata/ca.mordak.Term48.gYABgJC2m1SvBDfQMWQBsIohLnw/data/bin/crontab@main+0x1f3) ref=00000000
segmentation violation (core dumped)

bash-5.0$ md5sum packages/cronie-1.5.4.zip
78019665668ef696b1ab0bc8bb5b5bc6  packages/cronie-1.5.4.zip

</pre>

**Comment by vaskas** [comment]
Does v1.5.2 (the one we have in ports) work? Has it ever worked?

**Comment by berryamin** [comment]
I think at some point it did work ..  just commited 426cd8a08ecadcceec2fe4d9db64f7d62e5d7a21 to master (once PR #22 will be approved, I'll be able to work inside ports-wip  ), to re-add localestatedir=/var/tmp configure option. Might fix the issue, but I still have no build host ready .. will be ready in a few days I hope.

**Comment by vaskas** [comment]
Closing this issue as the port has been moved into `ports-wip`
