### ISSUE TITLE
gdb-7.12.zip: Exec format error

### ISSUE THREAD

**Issue by berryamin** [BerryFarm/berrymuch#20]
Isn't gdb supposed to be compiled for target ?

<pre>
bash-5.0$ gdb ./sbin/crond
bash: /accounts/1000/appdata/ca.mordak.Term48.gYABgJC2m1SvBDfQMWQBsIohLnw/data/bin/gdb: cannot execute binary file: Exec format error
bash-5.0$ file bin/gdb
bin/gdb: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0xccca3b1309d71f536d1c11ce85f2217e37ccdc66, not stripped
bash-5.0$ ls -l packages/gdb-7.12.zip
-rw-rw-r-- 1 101581000 10158 19517969 Dec 21 06:25 packages/gdb-7.12.zip
bash-5.0$ md5sum packages/gdb-7.12.zip
987f7af28116341ba7746e9b95311d06  packages/gdb-7.12.zip

</pre>

**Comment by vaskas** [comment]
@berryamin `CONFIGURE_CMD="./configure --prefix=$PREFIX"` I believe this needs proper CC env variable

**Comment by vaskas** [comment]
Leaving this to you until after you download the VM :wink:

**Comment by berryamin** [comment]
I have added the relevant flags.
Now I hit a really strange issue with CFLAGS and LDFLAGS ..
<pre>
+ eval ./configure --prefix=/accounts/1000/shared/documents/clitools --host=arm-unknown-nto-qnx8.0.0eabi --build=i686-linux-gnu --target=arm-unknown-nto-qnx8.0.0eabi CFLAGS=-I../gmp-6.1.2 'LDFLAGS="-lgmp' '-L../gmp-6.1.2"'
++ ./configure --prefix=/accounts/1000/shared/documents/clitools --host=arm-unknown-nto-qnx8.0.0eabi --build=i686-linux-gnu --target=arm-unknown-nto-qnx8.0.0eabi CFLAGS=-I../gmp-6.1.2 'LDFLAGS=-lgmp -L../gmp-6.1.2'
configure: warning: CFLAGS=-I../gmp-6.1.2: invalid host type
configure: warning: LDFLAGS=-lgmp -L../gmp-6.1.2: invalid host type
configure: error: can only configure for one host and one target at a time
</pre>

I've pushed the following branch .. 
https://github.com/BerryFarm/berrymuch/tree/issue-20-gdb-build

would appreciate any help/tips ..

**Comment by berryamin** [comment]
Trying with the exact same flags as gcc 4.6.3 right now, gdb 7.4, then 7.5.1 (same century than gcc 4.6.3).
Up to now, 
<pre>
configure: error: "*** Gdb does not support native target arm-unknown-nto-qnx8.0.0eabi"
</pre>

**Comment by berryamin** [comment]
ok let's fetch it from community.qnx.com !

**Comment by berryamin** [comment]
Ok, no need to compile anything the binaries are available for Linux, Darwin, nto

http://community.qnx.com/sf/frs/do/listReleases/projects.toolchain/frs.gdb
