### ISSUE TITLE
Upgrade gcc port to 4.9.3

### ISSUE THREAD

**Issue by yamsergey** [BerryFarm/berrymuch#28]
I’ve got access to foundry27 Portal and found that there are branches for NDK up to GCC 4.9. Did anyone try to build them?

**Comment by berryamin** [comment]
Did not try, but very excited about it !

**Comment by vaskas** [comment]
Haven't tried it, just curious what are the benefits of 4.9?

**Comment by yamsergey** [comment]
@vaskas well, I'm not a GCC dev, so don't know how crucial the changes. But I  thought that 3 years of development should have some impact. GCC 4.6.3 is from 2012 and GCC 4.9.3 is from 2015. And this is changelog:
https://gcc.gnu.org/gcc-4.9/changes.html

**Comment by berryamin** [comment]
At least there is support for atomic operations, which is something needed for many apps out there. Once we will have this, it will open the way to many more ports.

**Comment by berryamin** [comment]
@yamsergey are we allowed to clone the gcc-4.9 tree ? would be nice to clone it as a berryfarm project, so we can share efforts and patches :)

**Comment by berryamin** [comment]
@yamsergey we might create a dedicated gcc-4.9 branch here https://github.com/BerryFarm/gcc

**Comment by berryamin** [comment]
gcc-4.9 branch is ready;
https://github.com/BerryFarm/gcc/tree/gcc-4.9/gcc
https://github.com/BerryFarm/berrymuch/blob/master/ports-wip/gcc-4.9/build.sh

**Comment by berryamin** [comment]
Tried to compile, much things successfull, but failure a this step:

make[2]: Leaving directory '/root/berrymuch/work/gcc-4.9/libcpp'
make[2]: Entering directory '/root/berrymuch/work/gcc-4.9/libdecnumber'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/berrymuch/work/gcc-4.9/libdecnumber'
make[2]: Entering directory '/root/berrymuch/work/gcc-4.9/gcc'
Makefile:26: *** missing separator.  Stop.
make[2]: Leaving directory '/root/berrymuch/work/gcc-4.9/gcc'
Makefile:4296: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/root/berrymuch/work/gcc-4.9'
Makefile:862: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vaskas** [comment]
I would check on the make version requirement. "Missing separator" is what I was getting trying to compile BSD Makefiles with GNU make.

**Comment by berryamin** [comment]
<pre>
(...)
make[2]: Entering directory '/root/berrymuch/work/gcc/gcc'
arm-unknown-nto-qnx8.0.0eabi-g++   -g -O2 -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc -Wl,-s  -o xgcc gcc.o ggc-none.o \
  c/gccspec.o  libcommon-target.a \
   libcommon.a ../libcpp/libcpp.a  -liconv ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a
gcc.o:(.data.rel.ro+0x84): undefined reference to `host_detect_local_cpu(int, char const**)'
collect2: ld returned 1 exit status
Makefile:1805: recipe for target 'xgcc' failed
make[2]: *** [xgcc] Error 1
make[2]: Leaving directory '/root/berrymuch/work/gcc/gcc'
Makefile:4296: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/root/berrymuch/work/gcc'
Makefile:862: recipe for target 'all' failed
make: *** [all] Error 2
root@52cdf4582094:~/berrymuch/ports-wip/gcc-4.9#
</pre>

**Comment by extrowerk** [comment]
I see gcc 8.3 too on the Foundry page. Is there any news about updating the toolchain?

**Comment by yamsergey** [comment]
As I got all our attempts has been failed so far :(

**Comment by extrowerk** [comment]
> As I got all our attempts has been failed so far :(

Which version did you tried?

**Comment by yamsergey** [comment]
> > As I got all our attempts has been failed so far :(
> 
> Which version did you tried?

I've tried 4.8.3 and 4.9.3

**Comment by vaskas** [comment]
Closing in favour of https://github.com/BerryFarm/berrymuch/issues/46
