### ISSUE TITLE
How can I trigger the media player using the /pps filesystem?

### ISSUE THREAD

**Issue by karawitan** [BerryFarm/berrymuch#29]
Hello,

   I'm trying to play with /pps filesystem .. It looks very interesting, could enable many things .. depending on Term48 app permissions, probably.

   First I have compiled a list of read-write files here on the wiki: https://github.com/BerryFarm/berrymuch/wiki/-dev-ro-and-rw-files

    Secondly I'm trying to stop/start/next the "Music" player ... (no success so far), using:

echo 'req:json:{"id":1, "cmd":"next"}' >> /pps/services/multimedia/mediaplayer/control
echo 'req:json:{"id":1, "cmd":"next"}' >> /pps/services/multimedia/mediacontroller/control

Any success on your side ? (maybe posting this to stackoverflow could bring more audience, as well ?)

**Comment by vaskas** [comment]
Where did you get the format for the commands?

**Comment by berryamin** [comment]
Out there, Sir :)
http://support7.qnx.com/download/download/26319/PPS_Objects_Reference.pdf

**Comment by berryamin** [comment]
Maybe we will be able to trigger media play from cli soon;

<pre>
bash-5.0$ touch /pps/services/multimedia/renderer/control
bash-5.0$ 

</pre>

http://www.qnx.com/developers/docs/qnxcar2/index.jsp?topic=%2Fcom.qnx.doc.qnxcar2.ppsref%2Ftopic%2Fmm-renderercontrol.html

<pre>
echo 'msg::inputAttach\ndat:json:{"ctxt":0, "url":"/macqnx/RCPS_SuckerPunchTH_M2_TestFile.mpg", "type":"track"}' >> /pps/services/multimedia/renderer/control
</pre>

**Comment by berryamin** [comment]
Tried this one, but no success so far .. 
Anyone to help with syntax ? 

$ exec 3<> /pps/services/multimedia/mediacontroller/control
$ echo "msg::b_down\nid::1\ndat::bid_next" >&3; cat <&3
@control
msg::m_active_pid
dat:n:83185921
@control
msg::m_active_gid
dat:n:10011
@control
msg::m_state
dat::playing
@control
res::b_down
id::1
error::badparam

**Comment by vaskas** [comment]
This has been achieved! We should now package these scripts with Berrymuch.

**Comment by karawitan** [comment]
done 
https://github.com/BerryFarm/berrymuch/blob/master/ports/contrib/bin/player
