### ISSUE TITLE
Compiling graphics dependent services?

### ISSUE THREAD

**Issue by patrickjquinn** [BerryFarm/berrymuch#40]
So what are the criteria for cross compiling of applications? Do they need to be originally configured to build on NetBSD or is that just drivers? Are we only talking about cli services?

If I wanted to recompile the arm source of say Firefox, what would be the blockers? Is it that its expecting Xorg / Wayland libraries (which BB10 obviously can't support) or is it something more fundamental that that.

Using the tool chain thats being used to build these utilities, could the likes of the latest NetBSD FF code base be portable to QNX/BB10.

**Comment by berryamin** [comment]
@patrickjquinn The first potential blocker would be, IMHO, the compiler. We have gcc 4.6.3, gcc 4.8.3 currently available for qnx/nto ... which are quite old . Which compiler does Firefox need ?

**Comment by patrickjquinn** [comment]
It actually looks like it’ll compile back to 4.6 based on the build compat matrix on Mozilla’s site. The other dependencies would be worth checking too, most notably libgtk+ and libpulse. 

It looks like it doesn’t require many dependencies outside of what you’ve already compiled.

The build guide looks like it might work with the GCC we have here. https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Cross-compiling_Mozilla

**Comment by berryamin** [comment]
"Due to the Java-based development system and inability to build C/C++ apps, the full Firefox browser will not be available on the Blackberry OS"
https://wiki.mozilla.org/Mobile/Platforms

**Comment by patrickjquinn** [comment]
Thy sounds like blackberry OS7 though. C/C++ support is obviously there for 10

**Comment by patrickjquinn** [comment]
Sounds like like they’re saying “due to blackberry apps being java only and not support C, we can’t build Firefox” which would have been true of 7 but not of 10, what do you think?

**Comment by berryamin** [comment]
"inability to build C/C++ apps" look very strange indeed. Maybe the instructions are very old ... I was not able to find the changelog of the wiki to check this ..

**Comment by berryamin** [comment]
But there is a fundamental question to be answered .. Which graphic library would FF use on BB10. I'm really not an expert on this side. Seems that qt5 might be an option.

**Comment by patrickjquinn** [comment]
Yep that’s what I’d imagine would be the target. Also another question is what BB10 running as a graphics server? Is it a Xorg based? Or is it something more exotic? If it’s the latter then it will be a pain in the balls to get this built but if it’s a something standard then we’re probably able to make an attempt.

If it’s something you think would be worthy of your time, we should pick a build, make a list of dependencies and set up a build script to automate the build process and give it a go.

IMO, the value of having a modern browser like FF would be a huge enabler for Blackberry devices in 2020.

Happy to try it alone if you don’t think it’s worth the effort 🙂

**Comment by berryamin** [comment]
The bb10 graphics server is called "Photon"

https://www.everything2.com/title/Photon+MicroGUI

**Comment by patrickjquinn** [comment]
Ah yes actually I’ve come across this... might be a problem but hard to tell until a build and run cycle is attempted

**Comment by vaskas** [comment]
Welcome Patrick! I saw your thread on CB. The best way to have a taste of cross-compiling anything is to try building Berrymuch and porting something new. You'll see a few things that need to be tweaked at the OS level however most patches are similar between the ports. I personally haven't looked into the graphical stuff for several reasons: Qt on BB10 is old (5.2) so the QtWebEngine is a no go anyway; No X11 or Wayland.  On the latter point, I would be looking into getting https://github.com/pelya/xserver-xsdl to run on our Android Runtime. At the moment it crashes - maybe there is a rogue native linux binary in the package. The SDL stuff itself should work.

**Comment by patrickjquinn** [comment]
Awesome stuff, thanks for the reply! I'll get digging into that stuff, it
was suggested (potentially by yourself) that if QT5 can be fixed up and
patched then upstream QT changes can be merged in and there is a
possibility of moving up a version of two after that.

I have my eye on CCPing Libspotify in order to get provide a backend for a
native BB10 Spotify app. If that build successfully i'll count that as a
win!

**Comment by berryamin** [comment]
@patrickjquinn where may I find the source code for CCPing Libspotify Sir ?

**Comment by patrickjquinn** [comment]
https://github.com/mopidy/libspotify-archive It's available here :) its actually no longer actively maintained and there is another project which does something similar but its based on Rust and AFIK we dont have Rust support...yet.

**Comment by vaskas** [comment]
@patrickjquinn for the native BB10 app you might want to try https://github.com/BerryFarm/blackberry-py-bootstrap which lets you build a GUI application with QML + Python using Tart. I had a brief stab at it (apart from getting the example to work) and it felt rather pleasant.

**Comment by extrowerk** [comment]
OFFTOPIC
Long time Haiku user/Haikuports member here with a handful years of porting experience, but less with actual programming. Got a PP lately and would like to bring my favorite and everyday-used programs to the platform. Will needs some time to actually start to send PRs because i already started to work again, so my time limited right now and Haiku also comes with a new release at the end of the month, so there will be also some assistance needed from my side. Whatever, thanks and keep up the good job!
/OFFTOPIC

**Comment by patrickjquinn** [comment]
A haiku ports member in the wild! I’m also a huge Haiku fan. Thanks for joining in with the development!

**Comment by extrowerk** [comment]
There are a handful others like me, but maybe not around here. Thanks for the kind words.

Btw, lemme refer to the Photon topic: Mplayer have Photon support (interestingly trough SDL but whatever). Have somebody tried to build it?

This project clearly needs a Telegram or irc channel!

**Comment by berryamin** [comment]
Welcome on board, sir https://t.me/berryfarm_org

**Comment by vaskas** [comment]
Closing this great topic - everyone is welcome in the Telegram channel.
