### ISSUE TITLE
Errors during install on device

### ISSUE THREAD

**Issue by extrowerk** [BerryFarm/berrymuch#42]
Just tried to install berrymuch 0.3 release on my PAssport and durin the install i was greeted with many python errors:
```ImportError: cannot import name sha512```

**Comment by extrowerk** [comment]
![E50F8FDC-80F0-4409-B082-A90F69FBF3A3](https://user-images.githubusercontent.com/5569059/83179153-e3704580-a121-11ea-8e98-0206af544edd.jpeg)

**Comment by berryamin** [comment]
@vaskas any idea what's going wrong ?

**Comment by extrowerk** [comment]
Wrong shell. In term48 works
