### ISSUE TITLE
Porting GCC 7.1

### ISSUE THREAD

**Issue by extrowerk** [BerryFarm/berrymuch#46]
I decided to attempt the bump from GCC 4.6.x to GCC7.1 from [Foundry27](http://foundry27.com/sf/scm/do/listRepositories/projects.toolchain/scm). This issue meant to tracke the progress and the dependencies, so we can better plan and organize things.

[GCC prerequisites](https://gcc.gnu.org/install/prerequisites.html) :
- [x] ISO C++11 compiler : Not needed, GCC4.6 should be able to bootstrap GCC7.1 from C.
- [x] C standard library and headers
- [x] GNAT: we don't need Ada support right now
- [x] A “working” POSIX compatible shell, or GNU bash: we have bash 5.
- [x] A POSIX or SVR4 awk : seems to be available
- [ ] GNU binutils: [work in progress](https://github.com/BerryFarm/berrymuch/pull/45)
- [x] gzip 1.2.4  or bzip2 1.0.2: gzip 1.5 available,
- [x] GNU make version 3.80 (or later): 3.82 in ports.
- [x] GNU tar version 1.14: 1.32 available
- [ ] Perl version between 5.6.1 and 5.6.24
- [x] GNU Multiple Precision Library (GMP) version 4.3.2: 61.2 recipe available in ports-wip, with minor changes it can build gmp from foundry27 too.
- [ ] MPFR Library version 3.1.0 (or later)
- [ ] MPC Library version 1.0.1 (or later)
- [ ] isl Library version 0.15 or later
- [ ] zstd Library

Depending on how much changes will be required other tools could be also required.
The list taken from the linked webpage, which meant to be used with the current GCC version (9.x AFAIK), thus maybe the version constraints aren't correct.

**Comment by extrowerk** [comment]
Please add a checkmark if you know a specific dependency already available.

**Comment by extrowerk** [comment]
Random quote from internet: 
"Latest versions as of 2017-06-19: gmp-6.1.2 mpfr-3.1.5 mpc-1.0.3 isl-0.16.1 cloog-0.18.4 gcc-7.1.0"
Now we know more about the version constraints.

**Comment by vaskas** [comment]
Sounds like Perl is a soft dependency. Even if not I imagine it would be happy with the host version.

**Comment by extrowerk** [comment]
Maybe we could close this.
