### ISSUE TITLE
Term49: include "berrymuch bootstrap"

### ISSUE THREAD

**Issue by karawitan** [BerryFarm/berrymuch#60]
To simplify installation of Berrymuch via Term49,
I'd suggest to add curl/wget, cacert to ../app/native/root/bin, and a script to download / install Berrymuch from github.com

Would improve the user experience, don't you think ?

**Comment by vaskas** [comment]
Great idea!

**Comment by karawitan** [comment]
Ok branch created on this purpose:

https://github.com/BerryFarm/Term49/tree/add-berrymuch-bootstrap

**Comment by karawitan** [comment]
Closing, as dev tokens are not available anymore
