### ISSUE TITLE
tmux not in bin folder?

### ISSUE THREAD

**Issue by 4drift** [BerryFarm/berrymuch#65]
I haven't had the ability to launch tmux since version 0.3, I'm not sure why.

In the instructions:
```
cd /accounts/1000/shared/misc/clitools
sh install.sh
```

I simply move clitools.zip and install.sh to /accounts/1000/shared/misc beforehand, the only thing I do different.

**Comment by karawitan** [comment]
Ok please check that you have a packages/ directory.
There are 2 packages needed : libevent and tmux
You have to unzip them at the right place.

**Comment by karawitan** [comment]
As far as I see in the documentation this point (how to uncompress an available Berrymuch package) is missing . So thank you very much for the feedback

**Comment by 4drift** [comment]
I do have libevent-2.0.22-stable.zip and tmux-2.0.zip in packages in /misc/clitools.

I did try to take the tmux binary from the other old blackberry I have from 0.3 and put it in $HOME/bin in this new 0.5 install. It wouldn't run, and chmod +x wouldn't work either.

I tried unzipping the tmux package to documents to look for a binary and I didn't see one. I saw tmux.1, tmux.c, tmux.h, and tmux.o in the main folder. Which is also the same files I see in the main folder /misc/clitools, no binary.

If there's a way to install it from the zip I'm not really sure how and I don't want to break anything.

**Comment by karawitan** [comment]
Ok then you may take the .zip files from 0.3 and unzip them below  ​/accounts/1000/shared/misc/clitools

**Comment by karawitan** [comment]
0.5 is a pre-release, not a final one. But everything is compatible, as the compiler is the same

**Comment by 4drift** [comment]
Okay, I got the zip file from packages tmux-1.9a unzipped it into /misc/clitools. I tried it in the subfolder tmux-1.9a which has share and bin folders within it, manpage being in the share folder.

I also tried copying just the tmux binary (I actually did this first) into /misc/clitools and that didn't work. Tried copying the tmux.1 file in there too just in case, that didn't work.

I tried adding /misc/clitools to path, and tried copying into $HOME/bin again. I am just getting permission denied.

**Comment by karawitan** [comment]
cd  /accounts/1000/shared/misc/clitools
unzip libevent-2.0.22-stable.zip
unzip tmux-2.0.zip 

Then you have /accounts/1000/shared/misc/clitools/bin/tmux

**Comment by karawitan** [comment]
are u on Telegram ? PM me at @kaloudov I'll help you

**Comment by karawitan** [comment]
Ok I think I got your problem. You said you launched install.sh from BerryMuch 0.5 ? did it ask for removal of previous BerryMuch version ?

**Comment by 4drift** [comment]
No I don't have telegram, or really any other chat apps.

I unzipped both at
/accounts/1000/shared/misc/clitools/libevent-2.0.22-stable/
/accounts/1000/shared/misc/clitools/tmux-2.0/

Re-ran the build script and selected None for replacing already there items -- and All for "replacing" all items two separate times. The latter of course yields nothing, as everything says permission denied.

This is a blackberry classic that just had a fresh install of 0.5 on it. I have an OLD classic with 0.3 on it I was attempting to take files off of to get tmux. So no there was not a previous version installed.

**Comment by karawitan** [comment]
ha non, they should not be dezipper under 
/accounts/1000/shared/misc/clitools/libevent-2.0.22-stable/
nor
/accounts/1000/shared/misc/clitools/tmux-2.0/

The zip archive contains bin/ lib/ etc. that go below /accounts/1000/shared/misc/clitools/ directly.

I wrote already the commands you have to type :

cd /accounts/1000/shared/misc/clitools
unzip libevent-2.0.22-stable.zip
unzip tmux-2.0.zip

Then you have /accounts/1000/shared/misc/clitools/bin/tmux

**Comment by 4drift** [comment]
Well now I have 263 files from tmux-2.0.zip in clitools folder and still no binary tmux to execute.

There was never a binary in that zip file, that was a problem from the beginning. I should have been more clear. I tried to outline all the things I tried *because* I never had a binary in version 0.5.k

While *tmux-1.9a.zip* (in version 0.3) had share/man/tmux.1 and bin/tmux in it's zip file, tmux-2.0 only ever had the files to compile tmux. I also tried using `gcc` to compile it and that didn't work, not that it would matter if there is no executable privileges on the file? Since I can't add it with `chmod +x` either.

And I tried to get tmux-1.9a every which way on there like I said before, but it never had executable abilities.

**Comment by karawitan** [comment]
the 2.0 version of tmux does not work.
Only 1.9a is working

**Comment by 4drift** [comment]
Well,  I had already tried to put the tmux 1.9a binary in /misc/clitools/bin folder in the file manager and got access denied, I also had already tried in `$HOME/bin` and no executable ability from the file itself stops it from working.

But I just did exactly the steps you said. And it still does not work.

https://i.imgur.com/IP1HyPX.png

**Comment by karawitan** [comment]
Hem ok this is embarrassing. These permissions issues are probably due to some bug in bb10, similar issue has been reported in the Telegram channel. So what does "ls -ld bin" give ?

**Comment by 4drift** [comment]
`drwxr-sr-x+ 2 101941000 1000_shared 20480 Dec 3 00:54 bin`

In file manager trying to unzip a package in /clitools NONE of the folders are accessible, all say "Can't unzip files to a read-only folder" actually.

With clitools 0.3 installed to documents on old phone: ONLY /clitools/lib is inaccessible.

**Comment by karawitan** [comment]
ok, so, please try this: chmod 777 bin (should not change anything, but strangelly, on my phone, it solved this kind of problem)
Then, try again unziping tmux-1.9 with libevent .
Then, put back the permissions to 755
I don't know what is the role of s here .. but it's interesting

**Comment by 4drift** [comment]
`chmod: changing permissions of 'bin/': Operation not permitted`

Then I get the exact same error as before when attempting to unzip.

**Comment by karawitan** [comment]
Are you able to mv bin bin.old and back  ?

**Comment by 4drift** [comment]
Well... once I successfully did mv bin bin.old I no longer had `mv` command. :-D Heh. I lazily went to file manager and just renamed it there back to bin. File manager still says the folder is read only.

**Comment by karawitan** [comment]
Ok being able to move bin/ means that you'll be able to repair . 
I think the best to do is now to 
 - create a directory named "old"
 - move everything below /accounts/1000/shared/misc/clitools to /accounts/1000/shared/misc/clitools/old
 - re-install BerryMuch 0.3, or better, 0.4

I don't advise to install 0.5-rc , as they introduce a new prefix (we stripped clitools/, to get shorter path and performances improvements) . We have currently no clear procedure to switch from old to new prefix. 0.5 might also introduce an improved way to fetch / uncompress packages.

**Comment by 4drift** [comment]
Apologies for the delay in response. I have 0.4 installed now, and I can use tmux again. I wish I had installed that the first time. Now I see I cannot delete the "old" folder unfortunately, so it's just going to be there forever taking up space.

Anyways, thanks for all the help and the great work on berrymuch.

**Comment by karawitan** [comment]
Ok very happy to know that you managed finally to do it :)

**Comment by 4drift** [comment]
....So there's no way to delete the old folder taking up 2GBs?
