### ISSUE TITLE
Communication channels for Berrymuch OS

### ISSUE THREAD

**Issue by berryamin** [BerryFarm/berrymuch#9]
Having a Live community-driven knowledge base ( and chat ) like IRC or Gitter would be of great benefit to the project, IMHO.

Gitter brings the search engine to the mix, a very powerfull option

What do you think ?

**Comment by esad** [comment]
Freenode would be great. Btw. which IRC client for BB10 can you recommend?

**Comment by berryamin** [comment]
Hi @edad ! very happy to ear from you.
Channel #berrymuch now opened on irc.freenode.net :)
About the best bb10 native irc client .. I don't know yet.

**Comment by vaskas** [comment]
IRC sounds great for the comms. For the knowledge base I suggest the GitHub wiki pages.

**Comment by vaskas** [comment]
There is only one BB10 native client as far as I'm aware. Good thing is it's free software - https://github.com/pepijndevos/tincan. Works fine for me but not over SSL so I might have to switch to weechat on my server instead.

**Comment by berryamin** [comment]
What about BB10 Developers on Telegram ?
https://t.me/bb10dev

**Comment by vaskas** [comment]
@yamsergey are you on Telegram? If yes jump into https://t.me/berrymuch_os

**Comment by berryamin** [comment]
I'd like to setup this, to have a presence on both Telegram and irc, as some "deep geeks" may use irc only ...

https://github.com/FruitieX/teleirc

**Comment by berryamin** [comment]
BerryFarm presence over multiple communication channels (IRC, Telegram, etc.) might be possible via "Matrix Bridges"

https://matrix.org/bridges
